// Input descriptions
export const ageDescription = 'Your current age!'
export const incomeDescription = 'Your total after tax income on your path to retirement!'
export const totalSpendingDescription = 'This field should be your total annual spending while you are saving for retirement.'
export const assetsDescription = 'Your current net worth: all of your current assets minus all of your current debts.'
export const targetDescription = 'The target amount that you want to retire with!'
export const incomeGrowthDescription = 'The average annual growth of your income that you expect on your path to retirement. Value is a percent!'
export const stockAllocDescription = 'The percent of your portfolio in stocks!'
export const bondAllocDescription = 'The percent of your portfolio in bonds!'
export const cashAllocDescription = 'The percent of your portfolio in cash!'
export const stockReturnsDescription = 'The amount you expect your stocks to return on your path to retirement!'
export const bondReturnsDescription = 'The amount you expect your bonds to return on your path to retirement!'
export const returnsDescription = 'The returns you expect on your portfolio on your path to retirement!'
export const simsDescription = 'The number of simulations you want to run! The max is 10,000 due to computational time.'
export const lengthDescription = 'The length of the simulation! The max is 50 due to computational time.'
export const amountDescription = 'The total amount invested!'
export const curInvRetDescription = 'The returns of the current investment.'
export const potInvRetDescription = 'The expected returns of the potential investment.'
export const curInvFeesDescription = 'The fees of the current investment.'
export const potInvFeesDescription = 'The fees of the potential investment.'
export const expectedTaxesDescription = 'The expected taxes if the current investment is sold. Value is a percent.'

// Tool descriptions
export const BFDescription = 'FIRE Basic uses several key inputs including Income, Assets, and Spending as well as the historical returns of the S&P 500 to estimate your time to retirement.'
export const AFDescription = 'FIRE Advanced allows for customization of income growth, portfolio allocation, and portfolio returns to estimate your time to retirment!'
export const BEDescription = 'The Break Even tool allows visualization of the time it takes for a new investment to outpace an old investment after taxes are applied!'
export const MCDescription = 'The Monte Carlo tool uses standard Brownian motion process in conjunction with the historical volatility of the S&P 500 to simulate the growth of your portfolio!'